apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: elastic-agent-config
  namespace: default
  files:
    - agent.yml=elastic-agent.yml