apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-agent
  namespace: default
  labels:
    app: elastic-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: elastic-agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: elastic-agent
      annotations:
        configmap/checksum: "PLACEHOLDER_HASH"
    spec:
      containers:
      - name: elastic-agent
        image: docker.elastic.co/beats/elastic-agent-complete:8.17.3
        args: ["-c", "/etc/elastic-agent/agent.yml", "-e"]
        imagePullPolicy: IfNotPresent
        env:
        - name: FLEET_SERVER_ENABLE
          value: "false"
        - name: FLEET_URL
          value: "https://your-fleet-server:8220"
        - name: FLEET_ENROLLMENT_TOKEN
          value: "your-enrollment-token"
        - name: ELASTIC_AGENT_TAGS
          value: "kubernetes,production"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "200m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: agent-config
          mountPath: /etc/elastic-agent/agent.yml
          subPath: agent.yml
          readOnly: true
        - name: agent-data
          mountPath: /usr/share/elastic-agent/data
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        securityContext:
          runAsUser: 0
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: elastic-agent
      hostNetwork: true
      hostPID: true
      volumes:
      - name: agent-config
        configMap:
          name: elastic-agent-config
          defaultMode: 0600
      - name: agent-data
        emptyDir: {}
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
