name: Export Synthetics Monitors

on:
  #schedule:
    # Run daily at 2 AM UTC
    #- cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual trigger
  workflow_run:
    workflows: ["Import Synthetics Monitors"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  export-monitors:
    runs-on: ubuntu-latest
    # Run export in these cases:
    # 1. Manual trigger or scheduled run
    # 2. After successful import from push (always live)
    # 3. After successful manual import (we'll assume it was live since dry-runs shouldn't need export)
    if: |
      github.event_name != 'workflow_run' || (
        github.event_name == 'workflow_run' && 
        github.event.workflow_run.conclusion == 'success'
      )
    
    steps:
    - name: Debug workflow run event
      if: github.event_name == 'workflow_run'
      run: |
        echo "Workflow run event details:"
        echo "Event name: ${{ github.event_name }}"
        echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Workflow run event: ${{ github.event.workflow_run.event }}"
        echo "Workflow run name: ${{ github.event.workflow_run.name }}"
        echo "Workflow run status: ${{ github.event.workflow_run.status }}"
        echo "Triggering workflow: ${{ github.event.workflow_run.workflow_id }}"
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt
    
    - name: Export Synthetics Monitors
      env:
        KIBANA_URL: ${{ secrets.KIBANA_URL }}
        KIBANA_API_KEY: ${{ secrets.KIBANA_API_KEY }}
      run: |
        python .github/scripts/export-synthetics-monitors.py
    
    - name: Check for changes
      id: git-check
      run: |
        git add monitors/
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected in monitors"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected in monitors"
        fi
    
    - name: Commit and push changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add monitors/
        git commit -m "update synthetics monitors export - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push
    
    - name: Create Pull Request (optional)
      if: steps.git-check.outputs.changes == 'true' && github.event_name == 'schedule'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "update synthetics monitors export"
        title: "Automated Synthetics Monitors Export"
        body: |
          This PR contains the latest export of synthetics monitors from Kibana.
          
          **Export Details:**
          - Export timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          - Triggered by: Scheduled workflow
          
          Please review the changes before merging.
        branch: automated-synthetics-export
        delete-branch: true