name: Export Synthetics Monitors

on:
  #schedule:
    # Run daily at 2 AM UTC
    #- cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual trigger
  workflow_run:
    workflows: ["Import Synthetics Monitors"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  export-monitors:
    runs-on: ubuntu-latest
    # Run export after successful import workflows
    if: github.event_name != 'workflow_run' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    
    steps:
    - name: Check if export should proceed
      if: github.event_name == 'workflow_run'
      id: should-export
      run: |
        echo "Workflow run event details:"
        echo "Event name: ${{ github.event_name }}"
        echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
        echo "Workflow run event: ${{ github.event.workflow_run.event }}"
        echo "Workflow run name: ${{ github.event.workflow_run.name }}"
        echo "Workflow run status: ${{ github.event.workflow_run.status }}"
        echo "Head commit message: ${{ github.event.workflow_run.head_commit.message }}"
        
        # Check if this was a fresh import by looking for indicators
        if echo "${{ github.event.workflow_run.head_commit.message }}" | grep -i "fresh.import" > /dev/null; then
          echo "Fresh import detected - skipping export to preserve original Git files"
          echo "should_export=false" >> $GITHUB_OUTPUT
        else
          echo "Normal import detected - proceeding with export"
          echo "should_export=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Checkout repository
      if: github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true'
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Python
      if: github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      if: github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt
    
    - name: Export Synthetics Monitors
      if: github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true'
      env:
        KIBANA_URL: ${{ secrets.KIBANA_URL }}
        KIBANA_API_KEY: ${{ secrets.KIBANA_API_KEY }}
      run: |
        python .github/scripts/export-synthetics-monitors.py
    
    - name: Check for changes
      if: github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true'
      id: git-check
      run: |
        git add monitors/
        if git diff --staged --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected in monitors"
        else
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected in monitors"
        fi
    
    - name: Commit and push changes
      if: (github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true') && steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add monitors/
        git commit -m "update synthetics monitors export - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push
    
    - name: Create Pull Request (optional)
      if: (github.event_name != 'workflow_run' || steps.should-export.outputs.should_export == 'true') && steps.git-check.outputs.changes == 'true' && github.event_name == 'schedule'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "update synthetics monitors export"
        title: "Automated Synthetics Monitors Export"
        body: |
          This PR contains the latest export of synthetics monitors from Kibana.
          
          **Export Details:**
          - Export timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          - Triggered by: Scheduled workflow
          
          Please review the changes before merging.
        branch: automated-synthetics-export
        delete-branch: true