name: Test Status Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-status:
    name: test-status
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Simple test
      run: |
        echo "Testing status check functionality"
        echo "Workflow: ${{ github.workflow }}"
        echo "Job: ${{ github.job }}"
        echo "Event: ${{ github.event_name }}"
        echo "Actor: ${{ github.actor }}"
        
    - name: Always pass
      run: |
        echo "✅ Test status check completed successfully"
        echo "This job always passes to test status reporting"
    
    - name: Create summary
      run: |
        echo "## Test Status Check Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Test Details:**" >> $GITHUB_STEP_SUMMARY
        echo "- Workflow Name: Test Status Check" >> $GITHUB_STEP_SUMMARY
        echo "- Job Name: test-status" >> $GITHUB_STEP_SUMMARY
        echo "- Expected Status Check: Test Status Check / test-status" >> $GITHUB_STEP_SUMMARY
        echo "- Event Type: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Actor: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "- Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ✅ All tests passed" >> $GITHUB_STEP_SUMMARY